zh:
  languageName: ä¸­æ–‡
  languageCode: zh-CN
  weight: 1
  title: é‚“æ·æ–‡çš„å·¥ç¨‹åšå®¢
  contentDir: content/zh
  params:
    sidebar:
      emoji: "ğŸ§‘â€ğŸ’»"
      avatar:
        enabled: true
        local: true
        src: images/avatar.png
      subtitle: "Go / React / æ—¥æœ¬å·¥ç¨‹å®è·µ"

ja:
  languageName: æ—¥æœ¬èª
  languageCode: ja-JP
  weight: 2
  title: é„§æ·æ–‡ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒ–ãƒ­ã‚°
  contentDir: content/ja
  params:
    sidebar:
      emoji: "ğŸ§‘â€ğŸ’»"
      avatar:
        enabled: true
        local: true
        src: images/avatar.png
      subtitle: "Go / React / æ—¥æœ¬ã§ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒªãƒ³ã‚°"

en:
  languageName: English
  languageCode: en-US
  weight: 3
  title: "Toushobun's Engineering Blog"
  contentDir: content/en
  params:
    sidebar:
      emoji: "ğŸ§‘â€ğŸ’»"
      avatar:
        enabled: true
        local: true
        src: images/avatar.png
      subtitle: "Go / React / Engineering in Japan"
