baseURL: "https://toushobun.github.io/"
theme: "stack"
publishDir: "docs"

defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

languages:
  zh:
    languageName: ä¸­æ–‡
    languageCode: zh-CN
    weight: 1
    title: é‚“æ·æ–‡çš„å·¥ç¨‹åšå®¢

  ja:
    languageName: æ—¥æœ¬èª
    languageCode: ja-JP
    weight: 2
    title: é„§æ·æ–‡ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒ–ãƒ­ã‚°

  en:
    languageName: English
    languageCode: en-US
    weight: 3
    title: "Toushobun's Engineering Blog"

params:
  author:
    name: é‚“æ·æ–‡
    # email: toushobun@gmail.com
    # link: https://toushobun.github.io/

  sidebar:
    emoji: "ğŸ§‘â€ğŸ’»"
    subtitle: "Go / React / Engineering in Japan"

  # article:
    # toc: true
    # readingTime: true

  footer:
    since: 2025
