baseURL: "https://toushobun.github.io/"
theme: "stack"
publishDir: "docs"

## å¤šè¯­è¨€è®¾ç½®
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true
languages:
  zh:
    languageName: ä¸­æ–‡
    languageCode: zh-CN
    weight: 1
    title: é‚“æ·æ–‡çš„å·¥ç¨‹åšå®¢
    contentDir: content/zh
    params:
      sidebar:
        avatar:
          src: images/avatar.png
        emoji: "ğŸ§‘â€ğŸ’»"
        subtitle: "Go / React / æ—¥æœ¬å·¥ç¨‹å®è·µ"

  ja:
    languageName: æ—¥æœ¬èª
    languageCode: ja-JP
    weight: 2
    title: é„§æ·æ–‡ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒ–ãƒ­ã‚°
    contentDir: content/ja
    params:
      sidebar:
        avatar:
          src: images/avatar.png
        emoji: "ğŸ§‘â€ğŸ’»"
        subtitle: "Go / React / æ—¥æœ¬ã§ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒªãƒ³ã‚°"

  en:
    languageName: English
    languageCode: en-US
    weight: 3
    title: "Toushobun's Engineering Blog"
    contentDir: content/en
    params:
      sidebar:
        avatar:
          src: images/avatar.png
        emoji: "ğŸ§‘â€ğŸ’»"
        subtitle: "Go / React / Engineering in Japan"
translationKey: links

# ## èœå•é…ç½®
# menu:
#   main:
#     - identifier: home
#       name: Home
#       url: /
#       weight: 1
#       params:
#         icon: home

#     - identifier: archives
#       name: Archives
#       url: /zh/archives
#       weight: 2
#       params:
#         icon: archives

#     - identifier: search
#       name: Search
#       url: /search
#       weight: 3
#       params:
#         icon: search

#     - identifier: commands
#       name: Commands
#       url: /zh/commands
#       weight: 4
#       params:
#         icon: hash

## ä»£ç é«˜äº®é…ç½®
markup:
  highlight:
    noClasses: false

## è¯„è®ºç³»ç»Ÿé…ç½®
disqusShortname: toushobun

## å…¶ä»–å‚æ•°é…ç½®
params:
  article:
    toc: true

  footer:
    since: 2025

  comments:
    enabled: true
    provider: disqus

