baseURL: "https://toushobun.github.io/"
languageCode: "en-us"
title: "Toushobun's Engineering Notes"
theme: "PaperMod"

params:
  author: Toushobun
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true
