baseURL: "https://toushobun.github.io/"
theme: "PaperMod"
publishDir: "docs"

defaultContentLanguage: zh
defaultContentLanguageInSubdir: true
hasCJKLanguage: true

languages:

  en:
    languageName: English
    weight: 3
    contentDir: "content/en"
    title: "Toushobun's Engineering Blog"
    params:
      author: Toushobun

  zh:
    languageName: 中文
    weight: 1
    contentDir: "content/zh"
    title: 邓淞文的工程博客
    params:
      author: 邓淞文

  ja:
    languageName: 日本語
    weight: 2
    contentDir: "content/ja"
    title: 鄧淞文のエンジニアブログ
    params:
      author: 鄧 淞文

params:
  ShowReadingTime: true
  ShowCodeCopyButtons: true
