baseURL = "https://toushobun.github.io/"
theme = "PaperMod"
publishDir = "docs"

relativeURLs = false
canonifyURLs = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[languages]

  [languages.zh]
    languageName = "中文"
    weight = 1
    contentDir = "content/zh"
    title = "邓淞文的工程博客"

    [languages.zh.params]
      author = "邓淞文"

  [languages.ja]
    languageName = "日本語"
    weight = 2
    contentDir = "content/ja"
    title = "鄧淞文のエンジニアブログ"

    [languages.ja.params]
      author = "鄧 淞文"

  [languages.en]
    languageName = "English"
    weight = 3
    contentDir = "content/en"
    title = "Toushobun's Engineering Blog"

    [languages.en.params]
      author = "Toushobun"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true

  # [params.profileMode]
  #   enabled = true
  #   title = "邓淞文"
  #   subtitle = "Golang / React 全栈工程师"
  #   imageUrl = "/pic/avatar.png"
  #   imageTitle = "avatar"
  #   imageWidth = 60
  #   imageHeight = 60
