baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Toushobun's Engineering Notes"
theme = "PaperMod"

[params]
  author = "Toushobun"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
